name: Facebook Scraper

on:
  schedule:
    # minden 5. percben
    - cron: '*/5 * * * *'
  workflow_dispatch: # kézi futtatás lehetősége

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install requests
        run: pip install requests

      # Letöltjük az előző last_post artifact-et
      - name: Download last post artifact
        uses: actions/download-artifact@v3
        with:
          name: last-post
          path: ./last_post.txt
        continue-on-error: true

      - name: Run Facebook Scraper
        env:
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          WEBHOOK: ${{ secrets.WEBHOOK }}
          FACEBOOK_URL: "https://www.facebook.com/peter.magyar.102"
          ACTOR_ID: "KoJrdxJCTtpon81KY"
          LAST_POST_FILE: "last_post.txt"
        run: python mppost.py

      # Feltöltjük a friss last_post.txt-et artifactként
      - name: Upload last post artifact
        uses: actions/upload-artifact@v3
        with:
          name: last-post
          path: ./last_post.txt
